import HorizonScroll from './demos/HorizonScroll.jsx';
import TextReveal from './demos/TextReveal.jsx';
import ScrollGrowImage from './demos/ScrollGrowImage.jsx';
import CenterCarousel from './demos/CenterCarousel.jsx';
import DragCarousel from './demos/DragCarousel.jsx';
import MoreView from './demos/MoreView.jsx';
import InteractiveMap from './demos/InteractiveMap.jsx';
import Cylinder3D from './demos/Cylinder3D.jsx';
import HoverFollower from './demos/HoverFollower.jsx';
import FilterGallery from './demos/FilterGallery.jsx';
import WarpScroll from './demos/WarpScroll.jsx';
import GlassRefraction from './demos/GlassRefraction.jsx';

export const DEMOS = [
  {
    id: 'horizon-scroll',
    title: '가로 스크롤 섹션',
    desc: '세로 휠 입력을 가로 스크롤로 변환하는 스티키 섹션. 진행률 인디케이터 포함.',
    hint: '데모 영역 안에서 스크롤하세요',
    source: 'hallym',
    tags: ['sticky', 'wheel', 'indicator'],
    emoji: '↔️',
    thumb: 'linear-gradient(135deg,#1c72f2,#67e8f9)',
    component: HorizonScroll,
  },
  {
    id: 'text-reveal',
    title: '스크롤 텍스트 리빌',
    desc: 'hallym 메인 히어로 원본 이식 — 비디오 스케일업, 글자별 드롭인, 가로 전환 + 글자별 스윕 인.',
    hint: '글자가 다 나타난 뒤 스크롤하면 가로로 전환됩니다',
    source: 'hallym',
    tags: ['clip-path', 'stagger', 'video', 'horizontal'],
    emoji: '✂️',
    thumb: 'linear-gradient(135deg,#0f172a,#334155)',
    component: TextReveal,
  },
  {
    id: 'scroll-grow-image',
    title: '스크롤 이미지 확장',
    desc: 'vision.html 원본 이식 — 이미지가 85%→100%로 확장되며 올라오고, sticky 텍스트가 clip-path로 검정→흰색 반전.',
    hint: '데모 영역 안에서 스크롤하세요',
    source: 'hallym',
    tags: ['scroll-trigger', 'sticky', 'clip-path', 'color-invert'],
    emoji: '🖼️',
    thumb: 'linear-gradient(135deg,#16a34a,#bbf7d0)',
    component: ScrollGrowImage,
  },
  // {
  //   id: 'center-carousel',
  //   title: '센터모드 캐러셀',
  //   desc: 'slick 캐러셀을 React로 재구현. 가운데 슬라이드 확대 + 캡션 표시, 자동재생.',
  //   hint: '화살표를 누르거나 기다리면 자동으로 넘어갑니다',
  //   source: 'hallym',
  //   tags: ['carousel', 'autoplay', 'center-mode'],
  //   emoji: '🎠',
  //   thumb: 'linear-gradient(135deg,#7c3aed,#c4b5fd)',
  //   component: CenterCarousel,
  // },
  // {
  //   id: 'drag-carousel',
  //   title: '드래그 캐러셀',
  //   desc: '마우스/터치 드래그로 넘기는 캐러셀. 관성 스크롤과 스냅 지원.',
  //   hint: '슬라이드를 잡고 드래그하세요',
  //   source: 'hallym',
  //   tags: ['drag', 'pointer-events', 'snap'],
  //   emoji: '🫳',
  //   thumb: 'linear-gradient(135deg,#ea580c,#fed7aa)',
  //   component: DragCarousel,
  // },
  {
    id: 'more-view',
    title: 'More View 복제',
    desc: '버튼 클릭 시 이미지 그리드 블록을 복제해 이어붙이는 더보기 패턴.',
    hint: 'MORE VIEW 버튼을 클릭하세요',
    source: 'hallym',
    tags: ['clone', 'append', 'state'],
    emoji: '➕',
    thumb: 'linear-gradient(135deg,#475569,#cbd5e1)',
    component: MoreView,
  },
  // {
  //   id: 'interactive-map',
  //   title: '인터랙티브 맵',
  //   desc: '마커 호버 시 미리보기, 클릭 시 팝업, 사이드 버튼 토글이 연동되는 캠퍼스 맵.',
  //   hint: '마커에 호버하고, 건물 버튼을 클릭해 보세요',
  //   source: 'hallym',
  //   tags: ['hover', 'popup', 'toggle'],
  //   emoji: '📍',
  //   thumb: 'linear-gradient(135deg,#0ea5e9,#a5f3fc)',
  //   component: InteractiveMap,
  // },
  {
    id: 'cylinder-3d',
    title: '3D 원통 캐러셀',
    desc: 'index.html 원본 이식 — 링 안쪽 기울어진 시점(translateZ 910px + rotateY 30° + rotateZ 6°)에서 휠로 40°씩 회전.',
    hint: '데모 영역 위에서 휠을 굴리세요',
    source: 'good-portfolio',
    tags: ['css-3d', 'perspective', 'wheel'],
    emoji: '🥁',
    thumb: 'linear-gradient(135deg,#e5e7eb,#8CE457)',
    component: Cylinder3D,
  },
  // {
  //   id: 'hover-follower',
  //   title: '커서 추적 호버 이미지',
  //   desc: '리스트 행 위에서 커서를 따라다니는 프리뷰 이미지.',
  //   hint: '리스트 위에서 마우스를 움직여 보세요',
  //   source: 'good-portfolio',
  //   tags: ['mousemove', 'preview'],
  //   emoji: '🖱️',
  //   thumb: 'linear-gradient(135deg,#be185d,#fbcfe8)',
  //   component: HoverFollower,
  // },
  {
    id: 'filter-gallery',
    title: '필터 + 갤러리/리스트 전환',
    desc: '카테고리 필터, 갤러리↔리스트 레이아웃 토글, 6개씩 더보기가 결합된 보드.',
    hint: '필터와 레이아웃 버튼을 눌러 보세요',
    source: 'good-portfolio',
    tags: ['filter', 'layout-toggle', 'load-more'],
    emoji: '🗂️',
    thumb: 'linear-gradient(135deg,#65a30d,#d9f99d)',
    component: FilterGallery,
  },
  {
    id: 'warp-scroll',
    title: '종이 말림 스크롤 (Three.js)',
    desc: '스크롤 진행도에 따라 평면 지오메트리가 원통형으로 말리고 펴지는 버텍스 변형.',
    hint: '데모 영역 안에서 스크롤하세요',
    source: 'good-portfolio',
    tags: ['three.js', 'vertex', 'scroll-driven'],
    emoji: '📜',
    thumb: 'linear-gradient(135deg,#3730a3,#a5b4fc)',
    component: WarpScroll,
  },
  {
    id: 'glass-refraction',
    title: '유리 굴절 3D 로고 (Three.js)',
    desc: 'MeshPhysicalMaterial의 transmission으로 뒤 텍스트를 굴절시키는 유리 오브젝트.',
    hint: '마우스를 움직이면 시점이 살짝 이동합니다',
    source: 'good-portfolio',
    tags: ['three.js', 'transmission', 'env-map'],
    emoji: '🧊',
    thumb: 'linear-gradient(135deg,#111827,#93c5fd)',
    component: GlassRefraction,
  },
];
